app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
   path('', views.home, name='home'),
   path('register/', views.register, name='register'),
   path('login/', views.login, name='login'),
   path('logout', views.logout,name='logout'),
   path('userlist/', views.userlist, name='userlist'),
   path('changepassword/', views.changepassword, name='changepassword'),
]

login/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash


def home(request):
    return render(request, 'home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request, 'Invalid credentials!')
            return redirect("/login")
    else:
        return render(request, 'login.html')

    

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1==password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username already taken!')
                return redirect('/register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email already registered!')
                return redirect('/register')
            else:
                user = User.objects.create_user(
                    username=username,
                    password=password1,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                )
                user.save()
                messages.info(request, 'User registered!')
                return redirect('/login')
        else:
            messages.info(request, 'Passwords not matching!')
            return redirect('/register')
    else:
        return render(request, 'register.html')
    
def logout(request):
    auth.logout(request)
    return redirect('/')
        
@login_required
def userlist(request):
    users = User.objects.all
    return render(request, 'userlist.html', {"users": users})


@login_required
def changepassword(request):  
   if request.method=='POST':
       new_password1=request.POST['new_password1']
       new_password2=request.POST['new_password2']

       if new_password1==new_password2:
           user = request.user
           user.set_password(new_password1) 
           user.save()
           update_session_auth_hash(request, user)
           messages.success(request, 'Password changed successfully!')
           return redirect(reverse("app:changepassword"))
       else:
           messages.error(request, 'Password not matching!')
           return redirect(reverse("app:changepassword"))     
   else:
    return render(request, 'changepassword.html')

# !!!!!! to-do: fix redirect reverse!!!!!

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>{% block title %} Backend {% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-secondary">
            <div class="container-fluid">
              <a class="navbar-brand text-white fw-bold" href="#">Backend</a>
              <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon text-white"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active text-white" aria-current="page" href="{% url 'app:home' %}">Home</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'app:userlist' %}">User List</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ user.first_name }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <li><a class="dropdown-item text-dark" href="{% url 'app:changepassword' %}">Change Passoword</a></li>
                      <li><a class="dropdown-item text-dark" href="{% url 'app:logout' %}">Logout</a></li>
                    </ul>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'app:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'app:login' %}">Login</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>
    

app/templates/changepassword.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Change Password</h1>
    <form action="{% url 'app:changepassword' %}" method="POST">
        {% csrf_token %}
        <input type="password" name="new_password1" placeholder="new password" class="form-control mt-3">
        <input type="password" name="new_password2" placeholder="confirm new password" class="form-control mt-3">
        <input type="submit" value="Confirm Password" class="btn btn-primary text-white mt-3">
    </form>
</div>
<div class="container">
    {% if new_password1 == new_password2 %}
        {% for message in messages %}
            <div class="container mt-2 alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
</div>
        
    


{% endblock %}

app/templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container border border-secondary rounded mt-5 p-3">
    {% if user.is_authenticated %}
        <h1>Welcome, <strong>{{ user.first_name }}!</strong></h1>
    {% else %}
        <h1>Welcome, Guest!</h1>
    {% endif %}
</div>

<div class="container border border-secondary rounded mt-5 p-3">
    <p>This website was made to learn and practice login authentication with Django!</p>
    
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html'%}

{% block content %}
<div class="container border border-primary mt-3 p-3">
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username" class="form-control mt-2">
        <input type="password" name="password" placeholder="password" class="form-control mt-2">
        <input type="submit" value="Login" class="btn btn-primary mt-2">
    </form>
</div>

{% for message in messages %}
<div class="container mt-2 alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Register</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" name="first_name" placeholder="First Name" class="form-control mt-3">
            <input type="text" name="last_name" placeholder="Last Name" class="form-control mt-3">
            <input type="text" name="email" placeholder="email address" class="form-control mt-3">
            <input type="text" name="username" placeholder="username" class="form-control mt-3">
            <input type="password" name="password1" placeholder="password" class="form-control mt-3">
            <input type="password" name="password2" placeholder="confirm password" class="form-control mt-3">
            <input type="submit" value="Register" class="btn btn-primary text-white mt-3">
        </form>
    </div>
    <div class="container">
        {% for message in messages %}
        <p class="text-danger">{{ message }}</p>
        {% endfor %}
    </div>
{% endblock %}

app/templates/userlist.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>User List</h1>
    <ul class="list-group list-group-numbered">
        {% for user in users %}
        <li class="list-group-item">{{ user.username }}</li>
        {% endfor %}
    </ul>
    
</div>

{% endblock %}